name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t nginx_image:latest .

      - name: Set up Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/

      - name: Start Minikube cluster
        run: minikube start

      - name: Set Kubernetes context
        run: minikube update-context

      - name: Load Docker image into Minikube
        run: minikube image load nginx_image:latest
      
      - name: Deploy to Minikube
        run: minikube kubectl -- apply -f deployment.yaml

      - name: Test the application
        run: ./run_test_curl_on_server.sh

      - name: List Minikube Services
        run: minikube service list

      - name: Stop Minikube
        run: minikube stop
      
      - name: Delete Minikube
        run: minikube delete